--- 
environment: production 
chdir: /home/quark/webapp 
address: 127.0.0.1 
port: 4567
pid: /home/quark/webapp/thin.pid
rackup: /home/quark/webapp/config.ru 
log: /home/quark/webapp/log/thin.log
max_conns: 1024 
timeout: 30 
max_persistent_conns: 512 
daemonize: true
