defaults: &defaults
  :server:
    :domain: localhost
    :port: 5984

:development:
  <<: *defaults
  :databases:
    -
      :default: true
      :name: quarks_dev
:test:
  <<: *defaults
  :databases:
    -
      :default: true
      :name: quarks_test

:production:
  <<: *defaults
  :databases:
    -
      :default: true
      :name: quarks
